### ISSUE TITLE
server.jks(No such file)

### ISSUE THREAD

**Issue by JacksonLv** [jawi/ssl-socket-demo#3]
I just try your demo and when I run **Steps to run the server** . I got error as
 `Exception in thread "main" java.io.FileNotFoundException: server.jks (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at nl.lxtreme.ssl.socket.SslUtil.createKeyManagers(SslUtil.java:44)
	at nl.lxtreme.ssl.socket.SslUtil.createKeyManagers(SslUtil.java:36)
	at nl.lxtreme.ssl.socket.server.SslServer.getKeyManagers(SslServer.java:33)
	at nl.lxtreme.ssl.socket.SslUtil.createSSLContext(SslUtil.java:60)
	at nl.lxtreme.ssl.socket.SslUtil.createSSLServerSocket(SslUtil.java:65)
	at nl.lxtreme.ssl.socket.server.SslServer.createSSLSocket(SslServer.java:75)
	at nl.lxtreme.ssl.socket.server.SslServer.run(SslServer.java:47)
	at nl.lxtreme.ssl.socket.server.SslServer.main(SslServer.java:28)` .
 I am using java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-0ubuntu1.14.04.1)
OpenJDK Client VM (build 24.151-b01, mixed mode, sharing)

**Comment by jawi** [comment]
@JacksonLv : did you create the certificates and run the `copy_keystores.sh` script prior to running the code? As in: there should be both a `client.jks` file *and* a `server.jks` file in the `ssl.socket` directory.
